### ISSUE TITLE
不错 已学会使用

### ISSUE THREAD

**Issue by ketle** [wtser/ten-read#12]
已会自己加订阅 
顺便问下 下次会更新点啥

**Comment by wtser** [comment]
暂时还没有新的想法，不过可以改进添加订阅的方法

**Comment by ketle** [comment]
问下 插件数据2台电脑怎么同步？ 只有数据导出 没导入啊

**Comment by wtser** [comment]
数据是浏览器本地存储的。导入功能会有的。下个版本

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=ti&cv=7.7.29&pv=9.2.1&source=email_footer_2]
On 周三, 3月 23, 2016 at 21:50, ketle notifications@github.com wrote:
问下 插件数据2台电脑怎么同步？ 只有数据导出 没导入啊

**Comment by wtser** [comment]
2.0.5版本已经在审核中，支持了导入功能并修复了一些 bug
