### ISSUE TITLE
无法打开十阅里的链接

### ISSUE THREAD

**Issue by yangweijie** [wtser/ten-read#15]
https://ten-read.wtser.com/redirect?href=http%3A%2F%2Fizhongchou.taobao.com%2Fdreamdetail.htm%3Fid%3D20076238&title=%E3%80%8A%E7%A5%9E%E7%8A%AC%E5%B0%8F%E4%B8%83%E7%AC%AC%E4%B8%89%E5%AD%A3%E3%80%8B%E5%AE%98%E6%96%B9%E6%8E%88%E6%9D%83%E6%B8%B8%E6%88%8F%E6%95%B0%E6%8D%AE%E7%BA%BF

显示502 bad gatway

**Comment by wtser** [comment]
不再维护，推荐使用 https://github.com/wtser/simpleNews--web
